### ISSUE TITLE
无限次数喷漆无法使用

### ISSUE THREAD

**Issue by Tmdoofking** [LSDogX/CustomSprays#7]
无限次数喷漆无法使用
有限定次数是正常的

![image](https://github.com/LSDogX/CustomSprays/assets/70594985/1e17a072-b9c4-475b-866e-b9c4333cb163)

 - Server Version 1.19.2
 - Server Type Paper Spigot

**Comment by LSDogX** [comment]
bug 确认，这几天会修复

**Comment by LSDogX** [comment]
修复了，再次下载 [v1.5.8](https://github.com/LSDogX/CustomSprays/releases/tag/1.5.8) 就行了
